[package]
name = "moli"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
chrono = { version = "0.4", default-features = true, features = ["clock"] }
dirs = "5"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
unicode-width = "0.1"
